### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by emen**

### CODE REVIEW

**Comment by kyzn** [comment]
Thanks for joining Pull Request Club!

**Comment by emen** [comment]
Thank you @kyzn! I got this message `I can't confirm the PR on GitHub. If you think this is an error, please contact us.` when trying to mark the task as Done. Can you help please? Thanks!

**Comment by kyzn** [comment]
Hi @emen , apologies for the issue. I went ahead and marked the PR as done on your behalf. Thanks again for joining the Pull Request Club!

**Comment by emen** [comment]
Thank you @kyzn!

**Pull request merged**
